# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassName', models.CharField(max_length=100)),
                ('BaseAttBon', models.IntegerField(default=0)),
                ('Descrip', models.CharField(default='', max_length=300)),
                ('HitDie', models.IntegerField(default=6)),
                ('Abilites', models.CharField(default='', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RaceName', models.CharField(max_length=100)),
                ('Sizes', models.CharField(max_length=25)),
                ('Type', models.CharField(default='humanoid', max_length=100)),
                ('Speed', models.IntegerField(default=30)),
                ('StrMod', models.IntegerField(default=0)),
                ('DexMod', models.IntegerField(default=0)),
                ('ConMod', models.IntegerField(default=0)),
                ('IntMod', models.IntegerField(default=0)),
                ('WisMod', models.IntegerField(default=0)),
                ('ChaMod', models.IntegerField(default=0)),
                ('Languages', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpellName', models.CharField(max_length=100)),
                ('SpellDescrip', models.CharField(max_length=1000)),
                ('Save', models.CharField(max_length=50)),
                ('School', models.CharField(max_length=25)),
                ('Duration', models.CharField(max_length=50)),
                ('CastingTime', models.CharField(max_length=50)),
                ('Level', models.CharField(max_length=25)),
                ('Range', models.CharField(max_length=25)),
                ('Target', models.CharField(max_length=50)),
                ('SpellResist', models.CharField(default='yes', max_length=3)),
            ],
        ),
    ]
