# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0002_auto_20171206_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='Class',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='RaceName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='spell',
            old_name='SpellName',
            new_name='Name',
        ),
    ]
