# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0003_auto_20171207_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='Type',
            field=models.CharField(default='Humanoid', max_length=100),
        ),
        migrations.AlterField(
            model_name='spell',
            name='SpellResist',
            field=models.CharField(default='Yes', max_length=3),
        ),
    ]
