# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0006_auto_20171207_2039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clas',
            new_name='Class',
        ),
    ]
