# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0007_auto_20171207_2127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spell',
        ),
        migrations.AlterField(
            model_name='class',
            name='Abilites',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
