# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0008_auto_20171207_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='Abilites',
        ),
        migrations.RemoveField(
            model_name='class',
            name='BaseAttBon',
        ),
        migrations.RemoveField(
            model_name='class',
            name='Descrip',
        ),
        migrations.RemoveField(
            model_name='class',
            name='HitDie',
        ),
        migrations.RemoveField(
            model_name='race',
            name='ChaMod',
        ),
        migrations.RemoveField(
            model_name='race',
            name='ConMod',
        ),
        migrations.RemoveField(
            model_name='race',
            name='DexMod',
        ),
        migrations.RemoveField(
            model_name='race',
            name='IntMod',
        ),
        migrations.RemoveField(
            model_name='race',
            name='Languages',
        ),
        migrations.RemoveField(
            model_name='race',
            name='Sizes',
        ),
        migrations.RemoveField(
            model_name='race',
            name='Speed',
        ),
        migrations.RemoveField(
            model_name='race',
            name='StrMod',
        ),
        migrations.RemoveField(
            model_name='race',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='race',
            name='WisMod',
        ),
    ]
